[logging]
  level="info"

[sqlite]
  path="sqlite:///var/lib/chirpstack/chirpstack.sqlite"

[redis]
  url="redis://lora-redis:6379"

[network]
  net_id="000000"
  enabled_regions=["eu868"] # Replace with your region

[integration]
  enabled=["mqtt"]

  [integration.mqtt]
    server="tcp://lora-mqtt:1883"
    json=true
